language: php

php:
  - 8.0
  - hhvm

branches:
  except:
    - /^\d\.\d/

install:
  - composer install --no-dev

script: phpunit --configuration phpunit.xml.dist --coverage-text

after_success:
  - bash <(curl -s https://codecov.io/bash)
